### PR TITLE
Add tentative stockholm local hub for hackathon 2024

### PR DESCRIPTION
**Pull request by maxulysse**

### CODE REVIEW

**Review by FranBonath — APPROVED** [review]

**Comment by mashehu** [comment]
@nf-core-bot fix linting

**Comment by maxulysse** [comment]
> @nf-core-bot fix linting @mashehu I tried to fix the linting errors, but it didn't work. Please fix them manually.

you mentioned yourself?

**Comment by ewels** [comment]
> you mentioned yourself?

Is @mashehu also a GitHub actions bot? That would explain his levels of productivity..

**Comment by mashehu** [comment]
Nope, that's a bug in the fix linting action. It should be an extra comment.

**Pull request merged**
